### PR TITLE
CHanges made in configuration to allow user to change locale.

### PR DESCRIPTION
**Pull request by prashantbhardwaj**
One more properties file added for Hindi India.

### CODE REVIEW

**Comment by prashantbhardwaj** [comment]
Hi,

I am trying to get internationalization with Hindi (Indian language), but I am getting questions marks. Values of given properties are as follows:

subscription.email=ईमेल
subscription.type=प्रकार
subscription.submit=प्रेषित करें!
subscriptionType.ALL_EMAILS=सभी ईमेल
subscriptionType.DAILY_DIGEST=प्रतिदिन का पत्र

Could you please help get me desired results? Locale for Hindi is hi_IN.

**Comment by danielfernandez** [comment]
The JavaDoc for `java.util.Properties` establishes that the default encoding for Java `.properties` files is ISO-8859-1 (latin1), whatever the operating system and its default encoding.

You should therefore use Unicode escapes (`\uXXXX`) for your non-ASCII characters in the `.properties` file.

**Comment by prashantbhardwaj** [comment]
Thanks Daniel, however I am doing the same thing but no luck. Could you please check out this branch, place hindi values of property keys in property file (as given in my previous comment) and run the code to see if you get correct text in browser. Please

**Comment by danielfernandez** [comment]
All that was needed was to add a `Messages_hi.properties` file with the unicode-escaped characters, and then switch the encoding of the pages being returned (at the `ViewResolver`) to `UTF-8`, because the default is `ISO-8859-1` (Latin 1, for European languages), and obviously this encoding does not contain the right codes for Hindi language.

screen shot 2017-05-24 at 23 35 13

See the changes made here: thymeleaf/thymeleafexamples-thvsjsp@5fe0514c96d8f2d79891350b8aedff603244dac5

**Comment by prashantbhardwaj** [comment]
Thanks @danielfernandez It would be great, if you can merge these changes with master. Lot of Indians are working in IT sector and lot of work is happening in hindi language. Your code and comments will be very useful for all of them.

**Pull request closed without merging**
